name: Executar Script Python

on:
  schedule:
    - cron: '15 11 * * *' 
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Instalar dependências
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          AMEI_USERNAME: ${{ secrets.AMEI_USERNAME }}
          AMEI_PASSWORD: ${{ secrets.AMEI_PASSWORD }}
          COOKIE: ${{ secrets.COOKIE }}

        run: |
          python app.py
